import logging
import asyncio
import traceback
import uuid
from datetime import datetime
from typing import List, Optional

from backend.database.models import IngestionStatus, SourceType
from backend.database.queries import (
    insert_data_chunks,
    update_data_source_status,
)
from backend.rag.processors import extract_text
from backend.rag.chunking import chunk_text
from backend.rag.embeddings import get_embeddings

logger = logging.getLogger(__name__)


async def extract_and_chunk_source(
    source_id: str,
    source_type: SourceType,
    *,
    content: Optional[str] = None,
    url: Optional[str] = None,
    raw_bytes: Optional[bytes] = None,
    token: Optional[str] = None,
    on_progress: Optional[callable] = None,
) -> list[str]:
    """Pass 1 of 3: Extract raw text from a source and split it into chunks.
    
    Does NOT call any embedding API — this is pure CPU/network work and can
    run concurrently across many sources safely.

    Updates source status to 'processing' at start.
    Raises on failure (caller must catch and update status to 'failed').

    Returns:
        list[str]: The text chunks ready for embedding.
    """
    await update_data_source_status(source_id, IngestionStatus.processing, token=token)

    # Download file bytes from Cloudinary URL if not already cached in memory
    if source_type in (SourceType.pdf, SourceType.image) and not raw_bytes and url:
        logger.info(f"[INGEST P1] Fetching bytes from URL for source {source_id}")
        try:
            import httpx
            async with httpx.AsyncClient(follow_redirects=True, timeout=30.0) as client:
                response = await client.get(url)
                response.raise_for_status()
                raw_bytes = response.content
                logger.info(
                    f"[INGEST P1] Fetched {len(raw_bytes)} bytes for {source_id} "
                    f"(content-type: {response.headers.get('content-type', 'unknown')})"
                )
        except Exception as fetch_err:
            raise RuntimeError(f"Failed to download file from URL '{url}': {fetch_err}")

    if source_type in (SourceType.pdf, SourceType.image) and not raw_bytes:
        raise ValueError(
            f"No raw bytes available for {source_type.value} source — "
            "file was not uploaded or URL is missing"
        )

    # Extract plain text
    logger.info(f"[INGEST P1] Extracting text from source {source_id} (type={source_type.value})")
    extracted_text = await extract_text(
        source_type,
        content=content,
        url=url,
        raw_bytes=raw_bytes,
        on_progress=on_progress,
    )

    if not extracted_text.strip():
        raise ValueError("The provided source did not contain any readable text.")

    logger.info(f"[INGEST P1] Extracted {len(extracted_text)} characters from source {source_id}")

    # Chunk the extracted text
    chunks = chunk_text(extracted_text)
    logger.info(f"[INGEST P1] Chunked into {len(chunks)} chunk(s) for source {source_id}")

    if not chunks:
        raise ValueError("Text splitting resulted in zero chunks")

    return chunks


async def store_source_chunks(
    bot_id: str,
    source_id: str,
    source_type: SourceType,
    chunks: list[str],
    embeddings: list[list[float]],
    token: Optional[str] = None,
) -> int:
    """Pass 3 of 3: Persist pre-computed chunk + embedding pairs to the database.

    Takes embeddings that were already generated by the caller (allowing 
    the caller to batch-embed across ALL sources before calling this).

    Updates source status to 'completed' on success.

    Returns:
        int: Number of chunks stored.
    """
    if len(chunks) != len(embeddings):
        raise ValueError(
            f"Chunk/embedding mismatch for source {source_id}: "
            f"{len(chunks)} chunks vs {len(embeddings)} embeddings"
        )

    chunk_records = [
        {
            "id": str(uuid.uuid4()),
            "data_source_id": source_id,
            "bot_id": bot_id,
            "chunk_index": i,
            "content": text,
            "embedding": list(emb),
            "metadata": {
                "source_id": source_id,
                "type": str(source_type.value),
                "timestamp": datetime.utcnow().isoformat(),
                "total_chunks": len(chunks),
            },
            "created_at": datetime.utcnow().isoformat(),
        }
        for i, (text, emb) in enumerate(zip(chunks, embeddings))
    ]

    logger.info(f"[INGEST P3] Writing {len(chunk_records)} chunks to DB for source {source_id}")
    await insert_data_chunks(chunk_records, token=token)
    await update_data_source_status(source_id, IngestionStatus.completed, token=token)
    logger.info(f"[INGEST P3] ✅ Source {source_id} stored — {len(chunks)} chunks")

    return len(chunks)


async def ingest_source(
    bot_id: str,
    source_id: str,
    source_type: SourceType,
    *,
    content: Optional[str] = None,
    url: Optional[str] = None,
    raw_bytes: Optional[bytes] = None,
    token: Optional[str] = None,
) -> int:
    """Backward-compatible single-source ingestion: extract → embed → store.

    Used for single-document ingestion paths. For multi-doc batches, the
    ingestion_worker uses the 3-pass approach (extract all → batch embed once
    → store all) which is significantly faster.

    Returns:
        int: Number of chunks stored.
    """
    try:
        # Pass 1: Extract + chunk
        chunks = await extract_and_chunk_source(
            source_id=source_id,
            source_type=source_type,
            content=content,
            url=url,
            raw_bytes=raw_bytes,
            token=token,
        )

        # Pass 2: Embed (single source, single API call)
        logger.info(f"[INGEST] Generating embeddings for {len(chunks)} chunks (source {source_id})...")
        embeddings_manager = get_embeddings()
        embeddings = await asyncio.to_thread(embeddings_manager.embed_documents, chunks)
        logger.info(f"[INGEST] Embeddings generated (dim={len(embeddings[0])} each)")

        # Pass 3: Store
        return await store_source_chunks(
            bot_id=bot_id,
            source_id=source_id,
            source_type=source_type,
            chunks=chunks,
            embeddings=embeddings,
            token=token,
        )

    except Exception as e:
        err_msg = str(e) or repr(e) or type(e).__name__
        full_tb = traceback.format_exc()
        logger.error(f"[INGEST] Ingestion failed for source {source_id}: {err_msg}")
        logger.debug(f"[INGEST] Full traceback:\n{full_tb}")
        await update_data_source_status(source_id, IngestionStatus.failed, error=err_msg, token=token)
        raise
